name: flutter_fitness_ui
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_img: ^0.1.6+148

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu-Regular.ttf
          weight: 400
  
